language: python
python:
  - "2.7"
install: 
  - "pip install -r tests_requirements.txt"
  - "python setup.py install"
  - "pip install coveralls"
script: 
  - "coverage run runtests.py"
afterscript:
  - coveralls
